version: '3'
services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - database.env
  # Java application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory-local
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "8080:8080"
